#!/usr/bin/env bash
set -e

# Live-build config via auto/config (zonder niet-bestaande opties)
lb config noauto \
  --mode debian \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap http://deb.debian.org/debian \
  --mirror-chroot    http://deb.debian.org/debian \
  --mirror-binary    http://deb.debian.org/debian
