#!/usr/bin/env bash
set -euo pipefail

# Build SeniorenSlim ISO using live-build configuration in the 'iso' directory.
# This script should be run from anywhere inside the repository root.

# Determine the directory of this script and the project root
SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

ISO_DIR="$PROJECT_DIR/iso"
DIST_DIR="$PROJECT_DIR/dist"

# Inform the user
echo "[INFO] Starting live-build ISO generation from '$ISO_DIR'"

# Ensure the iso directory with live-build config exists
if [[ ! -d "$ISO_DIR" ]]; then
  echo "[ERROR] ISO configuration directory '$ISO_DIR' does not exist." >&2
  exit 1
fi

# Change to the iso directory to run live-build
cd "$ISO_DIR"

# Clean any previous builds
if command -v lb >/dev/null 2>&1; then
  echo "[INFO] Cleaning previous live-build artifacts (lb clean --all)"
  lb clean --all || true
else
  echo "[ERROR] 'lb' command not found. Please install live-build." >&2
  exit 1
fi

# Run live-build to create the ISO
echo "[INFO] Running 'lb build' to generate the ISO..."
lb build

# Find the generated ISO file (first .iso file in current directory)
ISO_FILE="$(find . -maxdepth 1 -type f -name '*.iso' | head -n 1 || true)"
if [[ -z "$ISO_FILE" ]]; then
  echo "[ERROR] No ISO file generated by live-build." >&2
  exit 1
fi

# Ensure dist directory exists
mkdir -p "$DIST_DIR"

# Move the generated ISO to the dist directory
TARGET_NAME="$(basename "$ISO_FILE")"
echo "[INFO] Moving ISO '$ISO_FILE' to '$DIST_DIR/$TARGET_NAME'"
mv "$ISO_FILE" "$DIST_DIR/$TARGET_NAME"

# Print success message
echo "[SUCCESS] ISO build completed. ISO located at: '$DIST_DIR/$TARGET_NAME'"
