name: Build SeniorenSlim ISO

on:
  push:
    branches: [ main ]
    paths:
      - 'iso/**'
      - 'scripts/B_build_iso.sh'
      - '.github/workflows/build-iso.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install live-build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            live-build debootstrap xorriso syslinux-utils squashfs-tools cpio ca-certificates curl

      - name: Ensure hook/scripts executable
        run: |
          chmod +x scripts/*.sh || true
          chmod -R +x iso/config/hooks || true

      - name: Build ISO
        run: sudo bash scripts/B_build_iso.sh

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: seniorenslim-iso
          path: dist/*.iso
