name: Build SeniorenSlim ISO

on:
  push:
    branches: [ main ]
    paths:
      - 'iso/**'
      - '.github/workflows/build-iso.yml'
  workflow_dispatch: {}   # handmatig starten vanuit Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Placeholder build (geen Docker nodig)
        run: |
          echo "ISO build placeholder. Triggered only for iso/** or manual run." 
          mkdir -p dist
          printf "Placeholder build at %s\n" "$(date -u)" > dist/README.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iso-placeholder
          path: dist/
