name: Build Docs (PDF)

on:
  push:
    branches: [ main ]
    paths:
      - 'assets/docs/*.md'
      - '.github/workflows/docs-pdf.yml'
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc & wkhtmltopdf
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends pandoc wkhtmltopdf fonts-dejavu fonts-liberation

      - name: Build PDFs
        run: |
          mkdir -p dist/docs
          if [ -f assets/docs/pandoc.css ]; then CSS="--css assets/docs/pandoc.css"; else CSS=""; fi
          if [ -f assets/docs/quickstart.md ]; then pandoc assets/docs/quickstart.md -o dist/docs/quickstart.pdf --pdf-engine=wkhtmltopdf --from markdown+emoji $CSS; fi
          if [ -f assets/docs/handleiding.md ]; then pandoc assets/docs/handleiding.md -o dist/docs/handleiding.pdf --pdf-engine=wkhtmltopdf --from markdown+emoji $CSS; fi
          if [ -f assets/docs/testrapport.md ]; then pandoc assets/docs/testrapport.md -o dist/docs/testrapport.pdf --pdf-engine=wkhtmltopdf --from markdown+emoji $CSS; fi

      - name: Upload artifact (PDFs)
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: dist/docs/

  publish-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          name: docs-pdf
          path: dist/docs

      - name: Upload PDFs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/docs/*.pdf
